added exec time

diff --git a/qubes-performance b/qubes-performance
--- a/qubes-performance
+++ b/qubes-performance
@@ -3,7 +3,7 @@
 #See usage().
 #
 #Copyright (C) 2021  David Hobach  GPLv3
-#version: 0.3
+#version: 0.4
 #
 #This program is free software: you can redistribute it and/or modify
 #it under the terms of the GNU General Public License as published by
@@ -133,12 +133,16 @@ local vm="$(b_args_get 0)"
 b_dom0_isHalted "$vm" || { B_ERR="The VM $vm must be halted." ; B_E }
 
 measure "t_qrexec_start"
-qvm-run -p "$vm" 'echo hello' < /dev/null > /dev/null || { B_ERR="Failed to execute qvm-run." ; B_E }
+qvm-run -p "$vm" 'date +%s%N &> /tmp/qubes-performance.txt ; echo hello' < /dev/null > /dev/null || { B_ERR="Failed to execute qvm-run." ; B_E }
 measure "t_qrexec_end"
 
 local crit_chain_system crit_chain_user
 crit_chain_system="$(b_dom0_execStrIn "$vm" "set -e -o pipefail ; systemd-analyze critical-chain | tail -n+4")" || { B_ERR="Failed to obtain the system critical chain." ; B_E }
 crit_chain_user="$(b_dom0_execStrIn "$vm" "set -e -o pipefail ; systemd-analyze --user critical-chain | tail -n+4")" || { B_ERR="Failed to obtain the user critical chain." ; B_E }
+TIMES["t_exec"]="$(b_dom0_execStrIn "$vm" "set -e -o pipefail ; cat /tmp/qubes-performance.txt ; rm -f /tmp/qubes-performance.txt")" || { B_ERR="Failed to obtain the system time." ; B_E }
+local re='^[0-9]+$'
+[[ ${TIMES["t_exec"]} =~ $re ]] || { B_ERR="Unexpected output from the VM $vm. Maybe an attack?" ; B_E }
+TIMES["t_exec"]="${TIMES["t_exec"]::-6}"
 
 if ! b_args_getOption "-k" > /dev/null ; then
   qvm-shutdown "$vm" || { B_ERR="Failed to shut down the VM $vm." ; B_E }
@@ -161,7 +165,8 @@ Linux:
 $(prefix "    " "$crit_chain_system")
   user critical-chain:
 $(prefix "    " "$crit_chain_user")
-  qrexec call: $(( ${TIMES["t_qrexec_end"]} - ${TIMES["t_xen_end"]} - ${TIMES["d_crit_system"]} )) ms
+  exec time: $(( ${TIMES["t_exec"]} - ${TIMES["t_xen_end"]} - ${TIMES["d_crit_system"]} )) ms (depends on clock sync)
+  qrexec return: $(( ${TIMES["t_qrexec_end"]} - ${TIMES["t_xen_end"]} - ${TIMES["d_crit_system"]} )) ms
 Overall: $(( ${TIMES["t_qrexec_end"]} - ${TIMES["t_qrexec_start"]} )) ms"
 }
 
